version: "3"
services:
  ganache:
    image: trufflesuite/ganache:latest
    ports:
      - "8545:8545"
    volumes:
      - ./ganache-data:/data
    command:
      - --host=0.0.0.0
      - --port=8545
      - --db=/data
      - --mnemonic=blockaudit mnemonic test

